name: AcFun Card CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: CI
    steps:
    - name: Repo checkout
      uses: actions/checkout@v2
      
    - name: Registry login
      uses: docker/login-action@v1.14.1
      with:
        registry: ${{ secrets.REGISTRY }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
        
    - name: Build & Push
      uses: docker/build-push-action@v2.9.0
      with:
        context: .
        push: true
        file: ./AcFunCard/Dockerfile
        tags: ${{ secrets.REGISTRY }}/acfun-card
